apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: fabio/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # pod name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: JWT_KEY
              value: "my-extreme-secure-key"
            - name: STRIPE_KEY
              value: "sk_test_51QL3WpAIlydG80wVvTlDzFGT4LefBWBCgkdlX4LeKuTFGFnJe0BU8lkTHrW52iOR23WyiUePR9Bphjp9Wq2QcdVD00iJ7M0Ip5"
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
